### ISSUE TITLE
Why overwrite the distributin my.conf file?

### ISSUE THREAD

**Issue by rsanzante** [deimosfr/ansible-mariadb#1]
I'm wondering why the distribution my.conf file is overwritten by this role instead of add a file in the conf.d directory Now, if a new MariaDB release includes a new setting in the my.cnf file role must be updated with that new configuration.

**Comment by deimosfr** [comment]
Hi,

Sorry for the very late answer. In my opinion, it's better to completely have the control of your configuration files instead of just overriding them. Let's suppose that you install a newer version of MariaDB which will add a new parameter that you don't want in the default configuration. You simply won't handle it.

In addition, having to override the default configuration file is a good solution to let specific cases adding their config in conf.d for overriding. Those specific cases are still fully under your control.

Hope I'm clear in my explaination

**Comment by rsanzante** [comment]
Ok, thanks for the answer :)
